// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bogccphgqpssbzypcbyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZ2NjcGhncXBzc2J6eXBjYnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNTQ5NTMsImV4cCI6MjA0OTkzMDk1M30.6AsiX9_V8wRrpQE9ZgR1u53Qel-qe2MuXXVYDWium_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);